### PR TITLE
Added "Less Blinding Tints" Cherry Display option

### PR DESCRIPTION
**Pull request by Spaicrab**
I'm not sure if the code for this is very good as I'm not used to writing in C, but it works.
Disabling the option needs a save to be loaded or a player respawn to take effect, as I don't know how to re-import the PLAYPAL lump, but other than that it should be fine.
I tried merging this with nugget-doom, but I was redirected here instead as the feature has quite a few issues.

Let me know if there are any issues or possible improvements with the code.

### CODE REVIEW

**Comment by Spaicrab** [comment]
I think it looks good!
I think it's ready to be merged, but maybe it's better if you try it out for yourself first, I do need some feedback.

**Comment by xemonix0** [comment]
The fact that this setting can't be toggled on the fly without reloading ideally needs to be addressed before merging.

I propose taking a look at how Nugget Doom's night vision setting works and doing something similar here. One possible approach is to have a separate internal palette (e.g. `byte alttintpal[14*768]`) instead of modifying `PLAYPAL`, initialize it _just once_ (e.g. in `V_InitColorTranslation()`, by `memcpy`ing the original palette into it and then working with it just like usual), and then using the correct palette (unmodified/alternate ("less blinding") one) in `ST_doPaletteStuff()`, depending on the setting. This is one way to go, but feel free to try other solutions if you think of something better.

**Comment by Spaicrab** [comment]
> The fact that this setting can't be toggled on the fly without reloading ideally needs to be addressed before merging.
> 
> I propose taking a look at how Nugget Doom's night vision setting works and doing something similar here. One possible approach is to have a separate internal palette (e.g. `byte alttintpal[14*768]`) instead of modifying `PLAYPAL`, initialize it _just once_ (e.g. in `V_InitColorTranslation()`, by `memcpy`ing the original palette into it and then working with it just like usual), and then using the correct palette (unmodified/alternate ("less blinding") one) in `ST_doPaletteStuff()`, depending on the setting. This is one way to go, but feel free to try other solutions if you think of something better.

That is EXACTLY what I tried to do (I still have a stash with it), but even just copying the playpal without any edits and trying to use it as the palette results in garbled bytes on the screen, and I have no idea why.
Anyways, I'll be trying to fix the issue in the next few days.

**Comment by xemonix0** [comment]
Superseded by #11.

**Pull request closed without merging**
